name: purewibe
favicon: null
layout_spectrum: 0.020157244987785816
typography_spectrum: 0.4436238668859005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2514809714630246
  lightness: 0.41960781207308173
  saturation: 0.44723895541392267
  rhythmicContrast: 0.444109377451241
purpose: []
